"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { Pixelify_Sans } from "next/font/google";

type GameState = "loading" | "ready" | "running" | "over";

/** Sprite files, all generated by `scripts/generate-game-art.mjs`. */
const SPRITE_SOURCES = {
  dogRunA: "/dino/dog-run-a.svg",
  dogRunB: "/dino/dog-run-b.svg",
  dogJump: "/dino/dog-jump.svg",
  rockSmall: "/dino/rock-small.svg",
  rockCluster: "/dino/rock-cluster.svg",
  boulder: "/dino/boulder.svg",
  standingStone: "/dino/standing-stone.svg",
  twig: "/dino/twig.svg",
  log: "/dino/log.svg",
  branch: "/dino/branch.svg",
  branchRock: "/dino/branch-rock.svg",
  pines: "/dino/pines.svg",
  shrub: "/dino/shrub.svg",
  cloud: "/dino/cloud.svg",
  hills: "/dino/hills.svg",
} as const;

type SpriteKey = keyof typeof SPRITE_SOURCES;
type Assets = Record<SpriteKey, HTMLImageElement>;

type ObstacleKind = {
  sprite: SpriteKey;
  width: number;
  height: number;
  /** Collision box inset from the sprite edges: [left, right, top]. */
  inset: readonly [number, number, number];
};

/** Rocks and sticks, drawn at their intrinsic size so the pixels stay crisp. */
const OBSTACLE_KINDS = {
  rockSmall: { sprite: "rockSmall", width: 36, height: 22, inset: [4, 5, 2] },
  rockCluster: { sprite: "rockCluster", width: 68, height: 22, inset: [4, 6, 2] },
  boulder: { sprite: "boulder", width: 36, height: 46, inset: [4, 5, 3] },
  standingStone: { sprite: "standingStone", width: 22, height: 50, inset: [3, 3, 3] },
  twig: { sprite: "twig", width: 44, height: 20, inset: [2, 4, 9] },
  log: { sprite: "log", width: 48, height: 18, inset: [3, 4, 2] },
  branch: { sprite: "branch", width: 40, height: 42, inset: [5, 9, 4] },
  branchRock: { sprite: "branchRock", width: 56, height: 42, inset: [4, 9, 4] },
} as const satisfies Record<string, ObstacleKind>;

type ObstacleKindKey = keyof typeof OBSTACLE_KINDS;

type Obstacle = {
  kind: ObstacleKindKey;
  x: number;
};

type Particle = {
  x: number;
  y: number;
  vx: number;
  vy: number;
  life: number;
  size: number;
};

const pixelFont = Pixelify_Sans({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
});

const CANVAS_HEIGHT = 210;
const GROUND_BAND = 14; // Strip of scree below the ground line.
const FLOOR_Y = CANVAS_HEIGHT - GROUND_BAND;
const DOG_X = 56;
const DOG_WIDTH = 64;
const DOG_HEIGHT = 52;
const GRAVITY = 2300;
const JUMP_VELOCITY = -720;
const BASE_SPEED = 260;
const MAX_SPEED = 480;
const DOG_FRAME_DURATION = 0.12;
const HIGH_SCORE_STORAGE_KEY = "dog-runner-high-score";
const BASE_SPAWN_DELAY = 1.6;
const MIN_SPAWN_DELAY = 0.75;
const MIN_GAP_BASE = 160;
const JUMP_TIME = 0.85;

// Parallax rates, as a fraction of the ground speed.
const SCENERY_RATE = 0.34;
const HILLS_RATE = 0.13;
const SKY_RATE = 0.045;

const HILLS_WIDTH = 480;
const HILLS_HEIGHT = 80;
const GROUND_STEP = 22;
const SCENERY_STEP = 168;
const SKY_STEP = 210;

const randomBetween = (min: number, max: number) => min + Math.random() * (max - min);
const formatScore = (value: number) => value.toString().padStart(5, "0");

/** Stable pseudo-random in [0, 1) so procedural layers don't flicker per frame. */
const hash = (n: number) => {
  const x = Math.sin(n * 127.1 + 311.7) * 43758.5453;
  return x - Math.floor(x);
};

const loadImage = (src: string) =>
  new Promise<HTMLImageElement>((resolve, reject) => {
    const image = new Image();
    image.src = src;
    image.onload = () => resolve(image);
    image.onerror = (err) => reject(err);
  });

const loadAssets = async (): Promise<Assets> => {
  const keys = Object.keys(SPRITE_SOURCES) as SpriteKey[];
  const images = await Promise.all(keys.map((key) => loadImage(SPRITE_SOURCES[key])));
  return Object.fromEntries(keys.map((key, index) => [key, images[index]])) as Assets;
};

export default function DogRunnerGame({ onExit }: { onExit: () => void }) {
  const containerRef = useRef<HTMLDivElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const ctxRef = useRef<CanvasRenderingContext2D | null>(null);
  const assetsRef = useRef<Assets | null>(null);

  const animationFrameRef = useRef<number | undefined>(undefined);
  const lastTimeRef = useRef<number>(0);
  const elapsedRef = useRef<number>(0);
  const distanceRef = useRef<number>(0);
  const spawnTimerRef = useRef<number>(0);
  const nextSpawnDelayRef = useRef<number>(BASE_SPAWN_DELAY);
  const scoreRef = useRef<number>(0);
  const highScoreRef = useRef<number>(0);
  const milestoneFlashRef = useRef<number>(0);

  const dogRef = useRef({
    y: FLOOR_Y - DOG_HEIGHT,
    vy: 0,
    isJumping: false,
    frameTimer: 0,
    frameIndex: 0,
  });

  const obstaclesRef = useRef<Obstacle[]>([]);
  const particlesRef = useRef<Particle[]>([]);
  const gameStateRef = useRef<GameState>("loading");

  const [isReady, setIsReady] = useState(false);

  const cancelAnimation = () => {
    if (animationFrameRef.current) {
      cancelAnimationFrame(animationFrameRef.current);
      animationFrameRef.current = undefined;
    }
  };

  const spawnDust = useCallback((count: number, spread: number) => {
    for (let i = 0; i < count; i += 1) {
      particlesRef.current.push({
        x: DOG_X + randomBetween(10, 42),
        y: FLOOR_Y - randomBetween(0, 4),
        vx: randomBetween(-140, -30),
        vy: randomBetween(-spread, -spread * 0.25),
        life: randomBetween(0.25, 0.5),
        size: Math.random() < 0.4 ? 3 : 2,
      });
    }
  }, []);

  const renderScene = useCallback(() => {
    const canvas = canvasRef.current;
    const ctx = ctxRef.current;
    if (!canvas || !ctx) {
      return;
    }

    const width = canvas.clientWidth;
    ctx.clearRect(0, 0, width, CANVAS_HEIGHT);
    ctx.imageSmoothingEnabled = false;

    const isDark = document.documentElement.classList.contains("dark");
    const ink = isDark ? "237,237,237" : "15,23,42";
    const textPrimary = `rgba(${ink},${isDark ? 0.9 : 0.88})`;
    const textSecondary = `rgba(${ink},0.55)`;
    const accent = isDark ? "#7ec9ff" : "#0d7fd1";

    const assets = assetsRef.current;
    if (!assets) {
      ctx.save();
      ctx.font = "600 22px 'Pixelify Sans', system-ui";
      ctx.fillStyle = textPrimary;
      ctx.textAlign = "center";
      ctx.fillText("Loading…", width / 2, CANVAS_HEIGHT / 2);
      ctx.restore();
      return;
    }

    const distance = distanceRef.current;
    const elapsed = elapsedRef.current;

    // ---- Sky: drifting clouds by day, a slow starfield by night ----------
    ctx.save();
    if (isDark) {
      const offset = distance * SKY_RATE * 0.6;
      const first = Math.floor(offset / 34);
      for (let i = first; i * 34 - offset < width + 34; i += 1) {
        const seed = hash(i * 2.3);
        if (seed > 0.62) continue;
        const x = Math.round(i * 34 - offset + seed * 26);
        const y = Math.round(12 + hash(i * 5.1) * 74);
        const twinkle = 0.3 + 0.35 * (1 + Math.sin(elapsed * 1.6 + i));
        ctx.fillStyle = `rgba(237,237,237,${(0.18 + seed * 0.3) * twinkle})`;
        ctx.fillRect(x, y, seed > 0.4 ? 1 : 2, seed > 0.4 ? 1 : 2);
      }
    } else {
      const offset = distance * SKY_RATE;
      const first = Math.floor(offset / SKY_STEP);
      ctx.globalAlpha = 0.85;
      for (let i = first; i * SKY_STEP - offset < width + SKY_STEP; i += 1) {
        const seed = hash(i * 3.7);
        if (seed > 0.72) continue;
        const x = Math.round(i * SKY_STEP - offset + seed * 90);
        const y = Math.round(14 + hash(i * 8.9) * 40);
        ctx.drawImage(assets.cloud, x, y, 32, 14);
      }
    }
    ctx.restore();

    // ---- Distant ridge line, tiled seamlessly ----------------------------
    ctx.save();
    ctx.globalAlpha = isDark ? 0.32 : 1;
    const hillsOffset = (distance * HILLS_RATE) % HILLS_WIDTH;
    for (let x = -hillsOffset; x < width; x += HILLS_WIDTH) {
      ctx.drawImage(assets.hills, Math.round(x), FLOOR_Y - HILLS_HEIGHT + 2, HILLS_WIDTH, HILLS_HEIGHT);
    }
    ctx.restore();

    // ---- Midground pines and shrubs --------------------------------------
    ctx.save();
    ctx.globalAlpha = isDark ? 0.6 : 1;
    const sceneryOffset = distance * SCENERY_RATE;
    const firstScenery = Math.floor(sceneryOffset / SCENERY_STEP);
    for (let i = firstScenery; i * SCENERY_STEP - sceneryOffset < width + SCENERY_STEP; i += 1) {
      const seed = hash(i * 1.9);
      const x = Math.round(i * SCENERY_STEP - sceneryOffset + seed * 120);
      if (seed < 0.5) {
        ctx.drawImage(assets.pines, x, FLOOR_Y - 30, 48, 30);
      } else if (seed < 0.78) {
        ctx.drawImage(assets.shrub, x, FLOOR_Y - 12, 20, 12);
        if (seed > 0.66) ctx.drawImage(assets.shrub, x + 26, FLOOR_Y - 12, 20, 12);
      }
    }
    ctx.restore();

    // ---- Ground line and scree -------------------------------------------
    ctx.save();
    ctx.fillStyle = `rgba(${ink},0.32)`;
    ctx.fillRect(0, FLOOR_Y, width, 2);
    const firstMark = Math.floor(distance / GROUND_STEP);
    for (let i = firstMark; i * GROUND_STEP - distance < width + GROUND_STEP; i += 1) {
      const seed = hash(i * 4.3);
      const x = Math.round(i * GROUND_STEP - distance + seed * 16);
      if (seed < 0.42) {
        ctx.fillStyle = `rgba(${ink},0.2)`;
        ctx.fillRect(x, FLOOR_Y + 3 + Math.round(seed * 16), 2 + Math.round(seed * 8), 2);
      } else if (seed < 0.72) {
        ctx.fillStyle = `rgba(${ink},0.14)`;
        ctx.fillRect(x, FLOOR_Y + 4 + Math.round(seed * 14), 2, 2);
      } else {
        // Grass tuft standing on the line.
        ctx.fillStyle = isDark ? "rgba(122,165,101,0.5)" : "rgba(122,165,101,0.85)";
        ctx.fillRect(x, FLOOR_Y - 4, 1, 4);
        ctx.fillRect(x + 2, FLOOR_Y - 6, 1, 6);
        ctx.fillRect(x + 4, FLOOR_Y - 3, 1, 3);
      }
    }
    ctx.restore();

    // ---- Obstacles --------------------------------------------------------
    for (const obstacle of obstaclesRef.current) {
      const kind = OBSTACLE_KINDS[obstacle.kind];
      ctx.drawImage(
        assets[kind.sprite],
        Math.round(obstacle.x),
        FLOOR_Y - kind.height,
        kind.width,
        kind.height,
      );
    }

    // ---- Dust ------------------------------------------------------------
    for (const particle of particlesRef.current) {
      ctx.fillStyle = `rgba(${ink},${Math.max(0, particle.life) * 0.55})`;
      ctx.fillRect(Math.round(particle.x), Math.round(particle.y), particle.size, particle.size);
    }

    // ---- Dog --------------------------------------------------------------
    const dog = dogRef.current;
    const dogSprite = dog.isJumping
      ? assets.dogJump
      : dog.frameIndex % 2 === 0
        ? assets.dogRunA
        : assets.dogRunB;
    ctx.drawImage(dogSprite, DOG_X, Math.round(dog.y), DOG_WIDTH, DOG_HEIGHT);

    // ---- HUD --------------------------------------------------------------
    const score = Math.floor(scoreRef.current);
    const highScore = Math.max(Math.floor(highScoreRef.current), score);

    ctx.save();
    ctx.textAlign = "right";
    ctx.fillStyle = milestoneFlashRef.current > 0 ? accent : textPrimary;
    ctx.font = "700 22px 'Pixelify Sans', system-ui";
    ctx.fillText(`SCORE ${formatScore(score)}`, width - 18, 34);
    ctx.fillStyle = textSecondary;
    ctx.font = "600 17px 'Pixelify Sans', system-ui";
    ctx.fillText(`HI ${formatScore(highScore)}`, width - 18, 58);
    ctx.restore();

    const gameState = gameStateRef.current;
    if (gameState === "ready") {
      ctx.save();
      ctx.font = "600 20px 'Pixelify Sans', system-ui";
      ctx.fillStyle = textSecondary;
      ctx.textAlign = "center";
      ctx.fillText("Tap or press space to start", width / 2, FLOOR_Y - 74);
      ctx.restore();
    } else if (gameState === "over") {
      ctx.save();
      ctx.font = "700 26px 'Pixelify Sans', system-ui";
      ctx.fillStyle = textPrimary;
      ctx.textAlign = "center";
      ctx.fillText("Game Over", width / 2, FLOOR_Y - 96);
      ctx.font = "600 18px 'Pixelify Sans', system-ui";
      ctx.fillStyle = textSecondary;
      ctx.fillText("Tap or press space to try again", width / 2, FLOOR_Y - 68);
      ctx.restore();
    }
  }, []);

  const resizeCanvas = useCallback(() => {
    const canvas = canvasRef.current;
    const container = containerRef.current;
    if (!canvas || !container) {
      return;
    }

    const context = canvas.getContext("2d");
    if (!context) {
      return;
    }

    const dpr = window.devicePixelRatio || 1;
    const width = container.clientWidth;
    canvas.style.width = `${width}px`;
    canvas.style.height = `${CANVAS_HEIGHT}px`;
    canvas.width = Math.floor(width * dpr);
    canvas.height = Math.floor(CANVAS_HEIGHT * dpr);
    context.setTransform(1, 0, 0, 1, 0, 0);
    context.scale(dpr, dpr);
    context.imageSmoothingEnabled = false;
    ctxRef.current = context;

    renderScene();
  }, [renderScene]);

  const resetGameState = useCallback(() => {
    const dog = dogRef.current;
    dog.y = FLOOR_Y - DOG_HEIGHT;
    dog.vy = 0;
    dog.isJumping = false;
    dog.frameTimer = 0;
    dog.frameIndex = 0;

    obstaclesRef.current = [];
    particlesRef.current = [];
    spawnTimerRef.current = 0;
    nextSpawnDelayRef.current = BASE_SPAWN_DELAY + Math.random() * 0.4;
    scoreRef.current = 0;
    milestoneFlashRef.current = 0;
    lastTimeRef.current = 0;
    // Distance carries the parallax layers, so start each run at a fresh spot
    // rather than snapping the scenery back to where it was last time.
    distanceRef.current = Math.random() * 4000;
  }, []);

  const updateHighScore = useCallback(() => {
    const score = Math.floor(scoreRef.current);
    if (score > highScoreRef.current) {
      highScoreRef.current = score;
      if (typeof window !== "undefined") {
        try {
          window.localStorage.setItem(HIGH_SCORE_STORAGE_KEY, String(highScoreRef.current));
        } catch {
          // Ignore storage failures (e.g. private mode).
        }
      }
    }
  }, []);

  const endGame = useCallback(() => {
    if (gameStateRef.current !== "running") {
      return;
    }
    updateHighScore();
    gameStateRef.current = "over";
    cancelAnimation();
    renderScene();
  }, [renderScene, updateHighScore]);

  /** Pick the rocks and sticks for one spawn, spaced out along the x axis. */
  const planPattern = useCallback((score: number, baseGap: number) => {
    const planned: { kind: ObstacleKindKey; offset: number }[] = [];
    let cursor = 0;

    const push = (kind: ObstacleKindKey, gapBefore = 0) => {
      cursor += gapBefore;
      planned.push({ kind, offset: cursor });
      cursor += OBSTACLE_KINDS[kind].width;
    };

    const longGap = baseGap * 1.2 + randomBetween(24, 48);
    const standardGap = baseGap + randomBetween(-14, 24);
    const shortGap = Math.max(120, baseGap * 0.85 + randomBetween(-10, 10));
    const pick = <T,>(options: readonly T[]) =>
      options[Math.floor(Math.random() * options.length)];

    if (score < 220) {
      // Warm-up: one low thing at a time.
      push(pick(["rockSmall", "twig", "log", "rockSmall"] as const));
      if (Math.random() < 0.2) push(pick(["rockSmall", "twig"] as const), longGap);
    } else if (score < 520) {
      const roll = Math.random();
      if (roll < 0.34) {
        push(pick(["boulder", "branch"] as const));
      } else if (roll < 0.68) {
        push(pick(["rockSmall", "log", "twig"] as const));
        push(pick(["rockSmall", "twig", "log"] as const), standardGap);
      } else {
        push(pick(["rockCluster", "branchRock"] as const));
      }
    } else {
      const roll = Math.random();
      if (roll < 0.3) {
        push(pick(["standingStone", "boulder", "branchRock"] as const));
      } else if (roll < 0.62) {
        push(pick(["boulder", "branch", "rockCluster"] as const));
        push(pick(["rockSmall", "twig", "log"] as const), standardGap);
      } else {
        const count = 3 + (Math.random() < 0.35 ? 1 : 0);
        for (let i = 0; i < count; i += 1) {
          push(pick(["rockSmall", "twig", "log", "boulder"] as const), i === 0 ? 0 : shortGap);
        }
      }
    }

    return planned;
  }, []);

  const updateGame = useCallback(
    (delta: number, width: number) => {
      if (gameStateRef.current !== "running") {
        return;
      }

      const assets = assetsRef.current;
      if (!assets) {
        return;
      }

      elapsedRef.current += delta;
      if (milestoneFlashRef.current > 0) {
        milestoneFlashRef.current -= delta;
      }

      const dog = dogRef.current;
      const wasAirborne = dog.isJumping;
      dog.vy += GRAVITY * delta;
      dog.y += dog.vy * delta;

      if (dog.y + DOG_HEIGHT >= FLOOR_Y) {
        dog.y = FLOOR_Y - DOG_HEIGHT;
        dog.vy = 0;
        dog.isJumping = false;
        if (wasAirborne) {
          spawnDust(7, 180);
        }
      }

      if (!dog.isJumping) {
        dog.frameTimer += delta;
        if (dog.frameTimer >= DOG_FRAME_DURATION) {
          dog.frameTimer = 0;
          dog.frameIndex = (dog.frameIndex + 1) % 2;
          if (dog.frameIndex === 0 && Math.random() < 0.5) {
            spawnDust(1, 60);
          }
        }
      } else {
        dog.frameTimer = 0;
        dog.frameIndex = 0;
      }

      const difficultyNormalized = Math.min(scoreRef.current / 900, 1);
      const currentSpeed = BASE_SPEED + difficultyNormalized * (MAX_SPEED - BASE_SPEED);
      distanceRef.current += currentSpeed * delta;

      spawnTimerRef.current += delta;
      const earlyEase = Math.max(0, 1 - scoreRef.current / 320);
      let minDelay = MIN_SPAWN_DELAY + earlyEase * 0.7 - difficultyNormalized * 0.25;
      minDelay = Math.max(minDelay, MIN_SPAWN_DELAY);
      let maxDelay = BASE_SPAWN_DELAY + 0.6 + earlyEase * 1.1 - difficultyNormalized * 0.55;
      if (maxDelay < minDelay + 0.25) {
        maxDelay = minDelay + 0.25;
      }

      if (spawnTimerRef.current >= nextSpawnDelayRef.current) {
        spawnTimerRef.current = 0;

        const jumpWindow = Math.min(JUMP_TIME, 0.55 + difficultyNormalized * 0.22);
        const baseGap = Math.max(
          MIN_GAP_BASE,
          currentSpeed * jumpWindow + 110 + earlyEase * 60,
        );

        let spawnBase = width + 48;
        const lastObstacle = obstaclesRef.current.at(-1);
        if (lastObstacle) {
          const lastKind = OBSTACLE_KINDS[lastObstacle.kind];
          spawnBase = Math.max(
            spawnBase,
            lastObstacle.x + lastKind.width + baseGap * 0.9,
          );
        }

        const pattern = planPattern(scoreRef.current, baseGap);
        for (const { kind, offset } of pattern) {
          obstaclesRef.current.push({ kind, x: spawnBase + offset });
        }

        nextSpawnDelayRef.current =
          randomBetween(minDelay, maxDelay) + Math.max(0, pattern.length - 1) * 0.18;
      }

      obstaclesRef.current = obstaclesRef.current
        .map((obstacle) => ({ ...obstacle, x: obstacle.x - currentSpeed * delta }))
        .filter((obstacle) => obstacle.x + OBSTACLE_KINDS[obstacle.kind].width > -20);

      particlesRef.current = particlesRef.current
        .map((particle) => ({
          ...particle,
          x: particle.x + (particle.vx - currentSpeed * 0.35) * delta,
          y: particle.y + particle.vy * delta,
          vy: particle.vy + 320 * delta,
          life: particle.life - delta,
        }))
        .filter((particle) => particle.life > 0 && particle.x > -8);

      const dogLeft = DOG_X + 12;
      const dogRight = DOG_X + DOG_WIDTH - 14;
      const dogTop = dog.y + 10;
      const dogBottom = dog.y + DOG_HEIGHT - 2;

      for (const obstacle of obstaclesRef.current) {
        const kind = OBSTACLE_KINDS[obstacle.kind];
        const [insetLeft, insetRight, insetTop] = kind.inset;
        const left = obstacle.x + insetLeft;
        const right = obstacle.x + kind.width - insetRight;
        const top = FLOOR_Y - kind.height + insetTop;

        if (dogLeft < right && dogRight > left && dogTop < FLOOR_Y && dogBottom > top) {
          endGame();
          return;
        }
      }

      const previousScore = Math.floor(scoreRef.current);
      scoreRef.current += delta * (120 + difficultyNormalized * 90);
      if (Math.floor(scoreRef.current / 100) > Math.floor(previousScore / 100)) {
        milestoneFlashRef.current = 0.6;
      }
    },
    [endGame, planPattern, spawnDust],
  );

  const step = useCallback(
    (timestamp: number) => {
      const canvas = canvasRef.current;
      if (!canvas) {
        return;
      }

      const delta = Math.min(
        0.05,
        (timestamp - (lastTimeRef.current || timestamp)) / 1000 || 0.016,
      );
      lastTimeRef.current = timestamp;

      updateGame(delta, canvas.clientWidth);
      renderScene();

      if (gameStateRef.current === "running") {
        animationFrameRef.current = requestAnimationFrame(step);
      }
    },
    [renderScene, updateGame],
  );

  const startLoop = useCallback(() => {
    resetGameState();
    gameStateRef.current = "running";
    renderScene();
    lastTimeRef.current = performance.now();
    animationFrameRef.current = requestAnimationFrame(step);
  }, [renderScene, resetGameState, step]);

  const handleAction = useCallback(() => {
    const gameState = gameStateRef.current;
    if (gameState === "loading") {
      return;
    }
    if (gameState === "ready" || gameState === "over") {
      dogRef.current.frameTimer = 0;
      dogRef.current.frameIndex = 0;
      startLoop();
      return;
    }
    const dog = dogRef.current;
    if (!dog.isJumping) {
      dog.vy = JUMP_VELOCITY;
      dog.isJumping = true;
      spawnDust(5, 120);
    }
  }, [spawnDust, startLoop]);

  useEffect(() => {
    let isCancelled = false;

    const setup = async () => {
      try {
        const assets = await loadAssets();
        if (isCancelled) return;
        assetsRef.current = assets;
        setIsReady(true);
      } catch (error) {
        console.error("Failed to load game assets", error);
        onExit();
      }
    };

    setup();

    return () => {
      isCancelled = true;
    };
  }, [onExit]);

  useEffect(() => {
    if (!isReady) {
      return;
    }

    resizeCanvas();
    resetGameState();
    gameStateRef.current = "ready";
    renderScene();

    const resizeObserver = new ResizeObserver(() => {
      resizeCanvas();
    });
    if (containerRef.current) {
      resizeObserver.observe(containerRef.current);
    }

    const onKeyDown = (event: KeyboardEvent) => {
      if (event.code === "Space" || event.code === "ArrowUp") {
        event.preventDefault();
        handleAction();
      } else if (event.code === "Escape") {
        event.preventDefault();
        onExit();
      }
    };

    const onPointerDown = (event: PointerEvent) => {
      event.preventDefault();
      handleAction();
    };

    window.addEventListener("keydown", onKeyDown);
    const canvas = canvasRef.current;
    canvas?.addEventListener("pointerdown", onPointerDown);

    const themeObserver = new MutationObserver(() => {
      if (gameStateRef.current !== "running") renderScene();
    });
    themeObserver.observe(document.documentElement, {
      attributes: true,
      attributeFilter: ["class"],
    });

    return () => {
      resizeObserver.disconnect();
      themeObserver.disconnect();
      cancelAnimation();
      window.removeEventListener("keydown", onKeyDown);
      canvas?.removeEventListener("pointerdown", onPointerDown);
    };
  }, [handleAction, isReady, onExit, renderScene, resetGameState, resizeCanvas]);

  useEffect(() => {
    if (typeof window === "undefined") {
      return;
    }
    const stored = window.localStorage.getItem(HIGH_SCORE_STORAGE_KEY);
    if (!stored) {
      return;
    }
    const value = Number.parseInt(stored, 10);
    if (!Number.isNaN(value) && value > highScoreRef.current) {
      highScoreRef.current = value;
      renderScene();
    }
  }, [renderScene]);

  useEffect(() => {
    return () => {
      cancelAnimation();
    };
  }, []);

  return (
    <div
      ref={containerRef}
      className={`${pixelFont.className} pointer-events-auto select-none`}
      style={{ height: `${CANVAS_HEIGHT}px` }}
    >
      <canvas ref={canvasRef} className="h-full w-full bg-transparent" height={CANVAS_HEIGHT} />
    </div>
  );
}
